# Generated by Django 3.1.4 on 2021-09-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('kb', 'kb'), ('graphs', 'graphs'), ('upload', 'upload'), ('vk', 'vk'), ('comparing', 'comparing'), ('admin', 'admin'), ('admin_all', 'admin_all'), ('admin_collection', 'admin_collection'), ('dashboards', 'dashboards'), ('bias', 'bias'), ('sms', 'sms'), ('call_schedule', 'call_schedule'))},
        ),
    ]
