# Generated by Django 3.1.4 on 2021-09-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210909_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorsOlap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('users_id', models.TextField()),
            ],
        ),
    ]
