# Generated by Django 3.1.4 on 2021-09-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210916_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersid',
            name='users_id',
            field=models.CharField(max_length=3000),
        ),
    ]
