# Generated by Django 3.1.4 on 2021-09-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210916_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersid',
            name='users_id',
            field=models.CharField(blank=True, editable=False, max_length=3000),
        ),
    ]
