# Generated by Django 3.1.4 on 2021-10-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210916_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersid',
            name='users_id',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
