"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path
import socket

# s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
# s.connect(("8.8.8.8", 80))
# HOST_NAME = s.getsockname()[0]
# s.close()


BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'l6(w@qv78w+kkljsdfoj7y8*Yi0u9pjekjhcoiy09H9ehcpo3j4%$ksq'

DEPLOY_HOST = '192.168.24.14'
DEV_HOST = '192.168.25.14'


# Флаг для разработки
DEBUG = True

# DEPLOY - флаг для prod версии, когда скрипт отрабатывает на prod сервере
DEPLOY = False

# if HOST_NAME == DEPLOY_HOST:
#     DEPLOY = True
#     DEBUG = False
# else:
#     DEPLOY = False

# ON_SERVER - флаг для face_verifier, чтобы указать, какая часть скрипта отрабатывает, если развернут на сервере
# if HOST_NAME == DEPLOY_HOST or HOST_NAME == DEV_HOST:
#     ON_SERVER = True
# else:
#     ON_SERVER = False
ON_SERVER = False

DEFAULT_FROM_EMAIL = 'analysis@some.ru'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'connect.smtp.bz'
EMAIL_USE_TLS = False
EMAIL_PORT = 2525
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
SERVER_EMAIL = 'analysis@some.ru'

ADMINS = [('User', 'test@test.com'),]

ALLOWED_HOSTS = ['127.0.0.1', DEPLOY_HOST, DEV_HOST, 'test.com', 'dev.test.team']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website',
    'crispy_forms',
    'sigma',
    'vk_app',
    'face_verifier',
    'user_visit',
    'actstream',
    'sms_delay',
    'call_schedule'
]
SITE_ID = 1

CRISPY_TEMPLATE_PACK = 'bootstrap4'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user_visit.middleware.UserVisitMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': 'django',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'django',
            'USER': 'django',
            'PASSWORD': '',
            'HOST': '',
            'PORT': '5432',
        }
    }

# Описаны настройки подключения к базам для использования в скриптах python
if DEPLOY:
    SLAVE_USER = ''
    SLAVE_PASSWORD = ''
    SLAVE_HOST = ''
    SLAVE_PORT = '5432'
    SLAVE_NAME = ''

    db_analytics = 'postgresql://name:password@127.0.0.1:5432/db_name'
    db_slave = 'postgresql://name:password@127.0.0.1:5432/db_name'
else:
    SLAVE_USER = ''
    SLAVE_PASSWORD = ''
    SLAVE_HOST = '127.0.0.1'
    SLAVE_PORT = '5432'
    SLAVE_NAME = ''

    db_analytics = 'postgresql://name:password@127.0.0.1:5432/db_name'
    db_slave = 'postgresql://name:password@127.0.0.1:5432/db_name'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_URL = '/static/'
'''
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
'''
if DEBUG:
    STATIC_DIR = os.path.join(BASE_DIR, 'static')
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static')
    ]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')
    STATICFILES_FINDERS = (
        'django.contrib.staticfiles.finders.FileSystemFinder',
        'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    )

LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/profile'
LOGOUT_REDIRECT_URL = '/login'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# if not DEBUG:
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        }
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

CIPHER_KEY = b'7839w268gefsdfjgbkjhef9823yfejwkg932ofhoi2kef9egfg9e2qdesf'

HEADERS_API = {
        'accept': 'application/json'
    }

URL_API = 'http://some_host_ip:8000/'

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 518400
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

SESSION_COOKIE_SECURE = True

CSRF_COOKIE_SECURE = True

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
