# Generated by Django 3.1.4 on 2021-09-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorsCallSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField()),
                ('termdelay', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
