# Generated by Django 3.1.4 on 2021-09-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollectorsCallSchedule',
            new_name='History',
        ),
    ]
